-- cl-web-enums.sql
-- $Id$
-- support for table-driven web pages
-- Lynn Dobbs and Greg Davidson

-- ** Copyright

--	Copyright (c) 2005 - 2008, J. Greg Davidson.
--	You may use this file under the terms of the
--	GNU AFFERO GENERAL PUBLIC LICENSE 3.0
--	as specified in the file LICENSE.md included with this distribution.
--	All other use requires my permission in writing.

-- * Concept: Attribute

CREATE TYPE html_attr_names AS ENUM (
'html_attr_accesskey',
'html_attr_action',
'html_attr_align',
'html_attr_alt',
'html_attr_axis',
'html_attr_border',
'html_attr_cellpadding',
'html_attr_cellspacing',
'html_attr_char',
'html_attr_charoff',
'html_attr_charset',
'html_attr_checked',
'html_attr_cite',
'html_attr_class',
'html_attr_classid',
'html_attr_codebase',
'html_attr_codetype',
'html_attr_cols',
'html_attr_colspan',
'html_attr_content',
'html_attr_content_type',
'html_attr_coords',
'html_attr_data',
'html_attr_datetime',
'html_attr_declare',
'html_attr_defer',
'html_attr_dir',
'html_attr_disabled',
'html_attr_enctype',
'html_attr_for',
'html_attr_frame',
'html_attr_headers',
'html_attr_height',
'html_attr_href',
'html_attr_http-equiv',
'html_attr_id',
'html_attr_ismap',
'html_attr_label',
'html_attr_longdesc',
'html_attr_maxlength',
'html_attr_media',
'html_attr_method',
'html_attr_multiple',
'html_attr_name',
'html_attr_nohref',
'html_attr_onblur',
'html_attr_onchange',
'html_attr_onclick',
'html_attr_ondblclick',
'html_attr_onfocus',
'html_attr_onkeydown',
'html_attr_onkeypress',
'html_attr_onkeyup',
'html_attr_onload',
'html_attr_onmousedown',
'html_attr_onmousemove',
'html_attr_onmouseout',
'html_attr_onmouseover',
'html_attr_onmouseup',
'html_attr_onreset',
'html_attr_onselect',
'html_attr_onsubmit',
'html_attr_profile',
'html_attr_readonly',
'html_attr_rel',
'html_attr_rev',
'html_attr_rows',
'html_attr_rowspan',
'html_attr_rules',
'html_attr_scheme',
'html_attr_scope',
'html_attr_scrolling',
'html_attr_selected',
'html_attr_shape',
'html_attr_size',
'html_attr_span',
'html_attr_src',
'html_attr_standby',
'html_attr_style',
'html_attr_tabindex',
'html_attr_target',
'html_attr_text',
'html_attr_title',
'html_attr_type',
'html_attr_usemap',
'html_attr_valign',
'html_attr_value',
'html_attr_valuetype',
'html_attr_width'
);

-- * Concept: Element
-- Deprecated and clunky formatting tages were left out
CREATE TYPE html_tags AS ENUM (
  'html_tag_foo',				-- groups elements
  'html_tag_bar',				-- dummy
  'html_tag_a',
  'html_tag_abbr',
  'html_tag_acronym',
  'html_tag_address',
  'html_tag_area',
  'html_tag_b',
  'html_tag_blockquote',
  'html_tag_body',
  'html_tag_br',
  'html_tag_button',
  'html_tag_caption',
  'html_tag_col',
  'html_tag_colgroup',
  'html_tag_dd',
  'html_tag_del',
  'html_tag_div',
  'html_tag_dl',
  'html_tag_dt',
  'html_tag_fieldset',
  'html_tag_form',
  'html_tag_h1',
  'html_tag_h2',
  'html_tag_h3',
  'html_tag_h4',
  'html_tag_h5',
  'html_tag_h6',
  'html_tag_head',
  'html_tag_hr',
  'html_tag_html',
  'html_tag_img',
  'html_tag_input',
  'html_tag_label',
  'html_tag_legend',
  'html_tag_li',
  'html_tag_link',
  'html_tag_map',
  'html_tag_meta',
  'html_tag_object',
  'html_tag_ol',
  'html_tag_optgroup',
  'html_tag_option',
  'html_tag_p',
  'html_tag_param',
  'html_tag_pre',
  'html_tag_q',
  'html_tag_script',
  'html_tag_select',
  'html_tag_span',
  'html_tag_style',
  'html_tag_sub',
  'html_tag_sup',
  'html_tag_table',
  'html_tag_tbody',
  'html_tag_td',
  'html_tag_textarea',
  'html_tag_tfoot',
  'html_tag_th',
  'html_tag_thead',
  'html_tag_title',
  'html_tag_tr',
  'html_tag_ul'
);
